application: secondhomebeta
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /js
  static_dir: js

# fonts
- url: /fonts
  static_dir: fonts
  
# lib
- url: /lib
  static_dir: lib

# Handler for all pages
# Login not required
- url: /.*
  script: secondhome.app
  
libraries:
- name: jinja2
  version: latest